Update README.md (#148)
Update the installation requirements.text because of the error

pip install -r requirements.txt
error: externally-managed-environment